apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: pader-portfolio-service
spec:
  selector:
   # Selector for Pods
    app: pader-portfolio-service
  type: LoadBalancer
  ports:
   # Port Map
  - protocol: TCP
    port: 8081
    targetPort: 80
    nodePort: 30001
